### ISSUE TITLE
Static ffprobe

### ISSUE THREAD

**Issue by ameingast** [Thefrank/ffmpeg-static-freebsd#1]
Thanks for this! Is there any way you could package a statically linked ffprobe together with ffmpeg and is there a way to get this binary into ports?

**Comment by Thefrank** [comment]
I added `ffprobe` to the release of 4.4. I have no great way of testing it so let me know how it works. (FATE tests ffmpeg only AFAIK)

As for ports...getting a static version of `ffmpeg` into ports would require all of the libraries that it uses to also give/add options to build them as static libraries. When I built 4.4 back in April most of the libraries either did not ship with, or worse, did not have the option to build them as static :(

**Comment by ameingast** [comment]
Thanks! I've performed some random tests with the ffprobe binary and it works just fine.

If shipping the static binaries in ports is unfeasible, maybe the build can be supplied to ffmpeg.org and be made available through the official website?
