### ISSUE TITLE
ffmpeg 4.4.1 binaries

### ISSUE THREAD

**Issue by derhuerst** [Thefrank/ffmpeg-static-freebsd#2]
Hey, author of `ffmpeg-static` here!

It would be great if you could build & upload the 4.4.1 binaries!

**Comment by Thefrank** [comment]
I didn't even notice an update, thanks for letting me know!
Unless you need it ASAP, I won't be able to get it updated until the weekend/early next week.

**Comment by Thefrank** [comment]
@derhuerst https://github.com/Thefrank/ffmpeg-static-freebsd/releases/tag/v4.4.1

Happy New Year! :)

**Comment by derhuerst** [comment]
Thanks!
