### ISSUE TITLE
Could you build FFMPEG v6 when you have time ?

### ISSUE THREAD

**Issue by HGStyle** [Thefrank/ffmpeg-static-freebsd#3]
Its all in the title.
When you have time to obviously !
Its not urgent.

**Comment by Thefrank** [comment]
FreeBSD ports version has also been updated to 6.0 so it should be much easier this time to update. I will also be adding chromaprint (requested), libzmq (requested), libsodium (needed for libzmq) and maybe one or two other missing codecs.

I hope to have something testable by the weekend

**Comment by HGStyle** [comment]
Oh i forgot, but could you disable GPL softwares while compilling please ?

**Comment by Thefrank** [comment]
> Oh i forgot, but could you disable GPL softwares while compilling please ?

most other packages have GPL'd software included (e.g., https://johnvansickle.com/ffmpeg/release-readme.txt). What would be the reason to not include them?

**Comment by Thefrank** [comment]
@HGStyle https://github.com/Thefrank/ffmpeg-static-freebsd/releases/tag/v6.0.0
