### ISSUE TITLE
Please add --extra-version to the buildconf of 7.0

### ISSUE THREAD

**Issue by kiryanov** [Thefrank/ffmpeg-static-freebsd#4]
Please add --extra-version=7.0 to the buildconf of 7.0 like it was with 5.* and 6.* releases, otherwise it's impossible to tell which version of ffmpeg is currently installed.

**Comment by Thefrank** [comment]
Looks like the script missed injecting the version number! I will get that fixed and reuploaded.

Thanks for letting me know!

**Comment by Thefrank** [comment]
@kiryanov Should be fixed now

**Comment by kiryanov** [comment]
Thanks a lot!
