### ISSUE TITLE
ffmpeg 7.0.2 and 7.1 binaries

### ISSUE THREAD

**Issue by lox** [Thefrank/ffmpeg-static-freebsd#5]
Might it be possible to get the binaries for 7.0.2 and 7.1?

**Comment by Thefrank** [comment]
I should have some time later this week to get them out

**Comment by Thefrank** [comment]
Added 7.0.2 and 7.1 to releases

**Comment by Thefrank** [comment]
@lox Closing. They have been uploaded. Do let me know if I missed other releases

**Comment by lox** [comment]
Appreciate your hard work @Thefrank!

**Comment by kailashchoudhary11** [comment]
@Thefrank @lox Can anyone please share the link where the static builds are uploaded for 7.1?
